import band.kessoku.scripts.gradle.plugin.PlatformIdentifier
import net.fabricmc.loom.util.ModPlatform

apply from: rootProject.file("gradle/scripts/klib-fabric.gradle")

base.archivesName = rootProject.name + "-keybinding"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)

    common("keybinding", ModPlatform.FABRIC)
    shadowBundle("keybinding", ModPlatform.FABRIC)
}
