import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-fabric.gradle")

base.archivesName = rootProject.name + "-keybinding"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)

    common("keybinding", PlatformIdentifier.FABRIC)
    shadowBundle("keybinding", PlatformIdentifier.FABRIC)
}
