import band.kessoku.scripts.gradle.plugin.PlatformIdentifier
import net.fabricmc.loom.util.ModPlatform

apply from: rootProject.file("gradle/scripts/klib-neo.gradle")

base.archivesName = rootProject.name + "-registry"

loom {
    accessWidenerPath = project(":registry-common").loom.accessWidenerPath
}

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)
    modules(["base"], PlatformIdentifier.NEO)

    common("registry", ModPlatform.NEOFORGE)
    shadowBundle("registry", ModPlatform.NEOFORGE)
}

remapJar {
    atAccessWideners.add("kessoku_registry.accesswidener")
}
