import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-neo.gradle")

base.archivesName = rootProject.name + "-entrypoint"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)

    common("entrypoint",PlatformIdentifier.NEO)
    shadowBundle("entrypoint", PlatformIdentifier.NEO)
}
