import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-neo.gradle")

base.archivesName = rootProject.name + "-event"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)
    modules(["base"], PlatformIdentifier.NEO)

    common("event", PlatformIdentifier.NEO)
    shadowBundle("event", PlatformIdentifier.NEO)
}
