import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-fabric.gradle")

base.archivesName = rootProject.name + "-entrypoint"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)

    common("entrypoint", PlatformIdentifier.FABRIC)
    shadowBundle("entrypoint", PlatformIdentifier.FABRIC)
}

dependencies {
}
