import band.kessoku.scripts.gradle.plugin.PlatformIdentifier
import net.fabricmc.loom.util.ModPlatform

apply from: rootProject.file("gradle/scripts/klib-neo.gradle")

base.archivesName = rootProject.name + "-command"

kessoku {
    modules(["base"], PlatformIdentifier.COMMON)
    modules(["base"], PlatformIdentifier.NEO)

    common("command", ModPlatform.NEOFORGE)
    shadowBundle("command", ModPlatform.NEOFORGE)
}
