import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-common.gradle")

base.archivesName = rootProject.name + "-entrypoint"

kessoku {
    modules(["base", "platform"], PlatformIdentifier.COMMON)
}

dependencies {
    implementation libs.aj4j
}
