modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/KessokuTeaTime/KessokuLib/issues"

[[mods]]
modId = "kessoku_events"
version = "${version}"
displayName = "Kessoku Lifecycle Events"
description = '''
Events for the game's lifecycle.
'''
logoFile = "icon.png"
authors = "Kessoku Tea Time"
displayURL = "https://modrinth.com/mod/kessoku-lib"

[[mixins]]
config = "kessoku_events.mixins.json"

[[mixins]]
config = "kessoku_events.neoforge.mixins.json"

#[[accessTransformers]]
#file = "META-INF/accesstransformer.cfg"

[[dependencies.kessoku_events]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kessoku_events]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"