import band.kessoku.scripts.gradle.plugin.PlatformIdentifier

apply from: rootProject.file("gradle/scripts/klib-fabric.gradle")

base.archivesName = rootProject.name + "-config"

kessoku {
    modules(["base", "platform"], PlatformIdentifier.COMMON)

    common("config", PlatformIdentifier.FABRIC)
    shadowBundle("config", PlatformIdentifier.FABRIC)
}

dependencies {
    shade(libs.aj4j)
}

shadowJar {
    relocate 'club.someoneice.json', 'band.kessoku.lib.shadow.json'
}